### PR TITLE
added the possibility of adding 4 self defined shortcuts, added optionspage, ...

### PR DESCRIPTION
**Pull request by Nibot1**
added the possibility of adding 4 self defined shortcuts and added an options page and adds the ability to decide if the search result should be shown in the popup or in a new Tab

### CODE REVIEW

**Comment by RameshAditya** [comment]
Hey @Nibot1, sorry for the delay, I'll test and merge this in a couple of hours. 🙂

**Comment by Nibot1** [comment]
does it work for you ?

**Comment by RameshAditya** [comment]
Awesome work, @Nibot1. This is great! Thank you. 😄

**Comment by Nibot1** [comment]
please change the id value in the manifest.json

**Comment by RameshAditya** [comment]
Yep, I've changed it. 

Although it seems to be optional after Firefox 48, based on the documentation here - https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/applications

**Comment by Nibot1** [comment]
you need it because as long as the extension is not published you will install ist via an unsigned-xpi file
look at here [https://developer.mozilla.org/en-US/Add-ons/WebExtensions/WebExtensions_and_the_Add-on_ID#When_do_you_need_an_add-on_ID](url)

**Pull request merged**
